# Generated by Django 2.0 on 2018-05-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='edu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.CharField(max_length=100)),
                ('sec', models.CharField(max_length=100)),
                ('almamater', models.CharField(max_length=100, verbose_name='AlmaMater')),
                ('period', models.DateTimeField()),
            ],
        ),
    ]
