# Generated by Django 2.0 on 2018-05-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('DoB', models.DateTimeField()),
                ('residence', models.CharField(max_length=100)),
                ('maritalstatus', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('hobbies', models.TextField()),
            ],
        ),
    ]
