# Generated by Django 2.0 on 2018-05-13 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_pdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdetails',
            name='residence',
        ),
    ]
